### ISSUE TITLE
请问安装的时候不能分区磁盘是什么问题啊？

### ISSUE THREAD

**Issue by ai930** [Tonymiugrey/Garden-by-miugrey#10]
HP SSD S700 1TB  
SAMSUNG MZVLB512HAJQ-000H1  (512 GB, PCI-E 3.0 x4)

我想在HP SSD S700 1TB 上分区安装mac系统可是不知道为什么分区不了。提示磁盘没用空间。可是我空间留的足够啊！

**Comment by Tonymiugrey** [comment]
应该是需要在那块硬盘上分一个ESP分区

**Comment by ai930** [comment]
我在SAMSUNG MZVLB512HAJQ-000H1 (512 GB, PCI-E 3.0 x4) 上可以格式化分区然后安装系统到第一步，可是接入第二步重启的时候就报：com.apple.documentmanager错误 
然而我的HP SSD S700 1TB磁盘在mac 系统的pe里面压根就格式化不了。。。。一格式化就报空间不足。可是我可以使用还原功能，我试着吧SAMSUNG MZVLB512HAJQ-000H1 (512 GB, PCI-E 3.0 x4) 分区的mac分区还原到HP SSD S700 1TB的mac分区。发现还是一样的错误。

**Comment by Tonymiugrey** [comment]
1.三星那个盘是PM981，本身不受苹果支持，不能直接安装黑苹果。请仔细阅读我的readme并按照要求操作，按理来说你在安装的时候是看不见那块盘的。按照要求操作，将macOS安装在HP那块盘上之后将macOS所在分区备份恢复至PM981
2.你需要在Windows下用Diskgenius为HP那块盘建立一个ESP分区，才能在安装器里对那块盘进行分区并安装macOS

**Comment by ai930** [comment]
我试过HP SSD S700 1TB（SATA-III ）安装，可是我格式化不了这个磁盘下的分区。进入苹果安装界面后无法使用自带的进行格式化。

**Comment by Tonymiugrey** [comment]
还看不懂吗？要在这块磁盘上先建立esp分区 才能在安装器里格式化！

**Comment by ai930** [comment]
ESP 分区只是存放引导文件的引导分区啊！

**Comment by Tonymiugrey** [comment]
实测mac安装器下进行分区时必须要有esp分区

**Comment by ai930** [comment]
OK ,那我试下

**Comment by ai930** [comment]
1.声卡有时候会突然驱动不了，重启可恢复。如果不行就多重启几次。

2.SSD（PM981）偶尔发烫，比Windows下正常使用烫。

这两个问题在 1.5 mac 10.14 下也有这样的情况吧！

**Comment by ai930** [comment]
我不用Paragon Hard Disk Manager 直接在mac pe下拷贝分区应该也是可以的吧！
