### ISSUE TITLE
ubs3.0不读盘

### ISSUE THREAD

**Issue by xxy9468615** [Tonymiugrey/Garden-by-miugrey#12]
读取不到ubs移动硬盘

**Comment by Tonymiugrey** [comment]
手上没有3.0的设备……你用2.0的设备应该没问题吧？3.0我打算最近研究一下…

**Comment by xxy9468615** [comment]
@Tonymiugrey  已经解决，从新定制以后，设备插入三分之二的时候可以读取，完全插入很大几率读取不到，具体原因不明确。

**Comment by Tonymiugrey** [comment]
能分享一下定制后的驱动吗 蟹蟹

**Comment by ghost** [comment]
Here is the USB 3.0 fix for this laptop !
Remove all fixes for usb and remove USBInjectAll.kext and put this kext on CLOVER folder !
[USBPorts.kext.zip](https://github.com/Tonymiugrey/Garden-by-miugrey/files/4862864/USBPorts.kext.zip)

**Comment by Tonymiugrey** [comment]
Thanks a lot!!

**Comment by Tonymiugrey** [comment]
I tried but it doesn't work... I create a new patch for my laptop then the USB works. I will add it next release.

**Comment by ghost** [comment]
The mapping of USB ports may be different depending on each submodel in the series Pavilion Gaming 15.
What model do you have ?

**Comment by Tonymiugrey** [comment]
I think so. I have the model 15-dk0xxx with i5-9300H, GTX1650 and 60Hz screen, sold in China.

**Comment by ghost** [comment]
I have same model but my screen have 144hz.

**Comment by Tonymiugrey** [comment]
Maybe there're some differences between the mother boards that adapt to different screens and sold in different country.

**Comment by w2016561536** [comment]
> @Tonymiugrey  已经解决，从新定制以后，设备插入三分之二的时候可以读取，完全插入很大几率读取不到，具体原因不明确。

你插入一半会被系统认为是USB 2.0，因为3.0的针脚很远，但是快速插到底就会是USB 3.0。
