### ISSUE TITLE
你好，固态硬盘发热有什么解决办法吗？屏幕有时候也会出现闪屏！

### ISSUE THREAD

**Issue by ai930** [Tonymiugrey/Garden-by-miugrey#13]

**Comment by Tonymiugrey** [comment]
固态发热暂时无解，可以去等一个叫nvmefix的kext，这个驱动暂时不稳定，不过应该是可以解决这个问题
闪屏？没遇到过，开了HIDPI了吗

**Comment by ai930** [comment]
嗯，开启HIDPI了后面稍微好点了，只是偶尔闪屏。这个驱动刚才看了，好像到1.0.2了

**Comment by Tonymiugrey** [comment]
1.0.2还不稳定 1.0.3好像全部重写了，不懂怎么样

**Comment by Tonymiugrey** [comment]
你是按我readme里面那个分辨率开的吗 我自从换成那个分辨率之后再也没闪过
