### ISSUE TITLE
有时候进不了系统

### ISSUE THREAD

**Issue by yuzhanglong** [Tonymiugrey/Garden-by-miugrey#14]
前辈您好，我的电脑（光影5）偶尔会进不去苹果系统，现象是这样的：在启动显示白色苹果标志读条的过程中上，后面半段走得很慢，等待几分钟之后进度条走满了，就一直卡在走满那里，没有任何反应，（这个现象偶尔发生，但之后强制关机重新打开又可以进入苹果系统）

**Comment by Tonymiugrey** [comment]
我猜可能是pm981的问题，因为我最早在sata盘上装的时候似乎是没有这个问题的……之后等pm981的解决方案成熟了再看看

**Comment by yuzhanglong** [comment]
| |
YuZhanglong
|
|
yuzl1123@163.com
|
好的，谢谢前辈，祝生活愉快。
在2020年06月17日 16:02，Miugrey<notifications@github.com> 写道：

我猜可能是pm981的问题，因为我最早在sata盘上装的时候似乎是没有这个问题的……之后等pm981的解决方案成熟了再看看

**Comment by Tonymiugrey** [comment]
哈哈哈没事  别这样，我才大一，可能还得叫您前辈/doge

**Comment by yuzhanglong** [comment]
| |
YuZhanglong
|
|
yuzl1123@163.com
|
太巧了，我也是大一，哈哈哈哈


在2020年06月17日 16:20，Miugrey<notifications@github.com> 写道：

哈哈哈没事 别这样，我才大一，可能还得叫您前辈/doge
