### ISSUE TITLE
type-c问题

### ISSUE THREAD

**Issue by yuzhanglong** [Tonymiugrey/Garden-by-miugrey#15]
你好，我今天在黑苹果上使用了扩展坞，经检测扩展坞上的USB可以连接使用，但是扩展坞上的hdmi无法使用，请问可以解决吗？

**Comment by Tonymiugrey** [comment]
个人猜测type c的输出要走核显的话可能得试试dp口，用hdmi的话大概率还是走独显……我之前借朋友的typeC屏幕剪片的时候，在Windows里发现是独显在输出
