### ISSUE TITLE
Can you release with OpenCore Bootloader?

### ISSUE THREAD

**Issue by arepson** [Tonymiugrey/Garden-by-miugrey#16]
With Big Sure macOS, recommended to used opencore Bootloader, can you release the EFI with OC?

**Comment by Tonymiugrey** [comment]
I know it's probably the only solution but the models sold in China are using Samsung PM981, the SSD which was poorly supported by macOS. It seems that Clover is the most suitable bootloader for this SSD now because the patches for PM981 only work with Clover. I will try to find the way that makes PM981 works on OC. Once I get it I will release the OC version at the first time. Thanks for your support!

**Comment by arepson** [comment]
My SSD PM981, now I install the Hackintosh in HDD.
Maybe you can check this link https://github.com/tylernguyen/x1c6-hackintosh/issues/43

**Comment by arepson** [comment]
Btw, PM981 support update system? Because we can't fresh install Hackintosh directly in PM981

**Comment by Tonymiugrey** [comment]
With my EFI, PM981 is working almost perfectly in the same way as the link that you posted, with HackrNVMeFamily-10_12_6_sec2018-001.kext and aml patch. I have tried Nvmefix.kext but it still has many problems. But it seems that HackrNVMeFamily-10_12_6_sec2018-001.kext was not supported by OC. Maybe the only way to use PM981 on OC is to wait for the stable version of nvmefix.kext.

I'm not sure because I updated to every version directly and successfully since 10.14.6 but failed in 10.15.5. Now I'm using 10.15.4. Soon I will make a backup, fix the EFI and try to update to 10.15.5 again.

**Comment by arepson** [comment]
Hi thanks for your contribution, I'm still waiting, good luck. And I hope you can fix the function keyboard (especially for Brightness, volume and media controll). You can check my DSDT in my repository (without PM981 support coz I'm install Hackintosh in HDD)

**Comment by arepson** [comment]
He used OC with PM981, Can you check it?
https://github.com/tylernguyen/x1c6-hackintosh/issues/43#issuecomment-630557272

**Comment by Tonymiugrey** [comment]
Function keys are normal in my  computer. You can copy pav15.aml in the ACPI folder of my efi.

**Comment by Tonymiugrey** [comment]
I check your EFI just now. You need to delete all the files in Clover/ACPI/patched and put "pav15.aml" in my EFI into this folder. Or maybe you can just try this one which will **disable PM981**. I modified that for you :)
[CLOVER.zip](https://github.com/Tonymiugrey/Garden-by-miugrey/files/4850000/CLOVER.zip)

**Comment by arepson** [comment]
Thanks 🙏 I will try it

**Comment by arepson** [comment]
Have you found a solution to update Hackintosh in PM981? I want to try a Hackintosh clone file on the HDD to PM981

**Comment by Tonymiugrey** [comment]
I directly updated for nearly 1 year, from 10.14.6 to 10.15.4, and just failed few days ago when I update to 10.15.5. I don't know why but if you want to try, you'd better create a backup.

**Comment by Tonymiugrey** [comment]
After clone it to PM981, please remember to replace the EFI with the [released version](https://github.com/Tonymiugrey/Garden-by-miugrey/releases)

It seems that you need to do a fresh install to HDD, then clone it to SSD. When you finished the installation on HDD, don't boot into macOS. Clone it to the SSD directly as I said in my readme.

**Comment by arepson** [comment]
> I directly updated to every version from 10.14.6 to 10.15.4 successfully but just failed a few days ago when I update to 10.15.5. I don't know why but if you want to try, you'd better create a backup.

How I can make backup? Can I backup full with the data and apps?

**Comment by arepson** [comment]
> After clone it to PM981, please remember to replace the EFI with the [released version](https://github.com/Tonymiugrey/Garden-by-miugrey/releases)
> 
> It seems that you need to do a fresh install to HDD, then clone it to SSD. When you finished the installation on HDD, don't boot into macOS. Clone it to the SSD directly as I said in my readme.

Maybe you can make released with latest version of Clover

**Comment by Tonymiugrey** [comment]
You can use Time Machine in macOS to backup your files, also Paragon Hard Disk Manager in Windows to backup the whole partition which you installed macOS. You will need the second one when you clone the OS to SSD.

**Comment by arepson** [comment]
Thanks for your help, but I still interesting with OC. I'm used this OC from Thunderobot (with similar hardware) but can't detect SATA/My HDD.
https://github.com/athlonreg/Thunderobot-911-Air-i7-9750h
I hope you can develop OC for Laptop HP Pavilion Gaming 15. Thanks for your help 🙏

**Comment by arepson** [comment]
What different CLOVER 1 and CLOVER2?

**Comment by Tonymiugrey** [comment]
Read the README first. Clover1 is used for installing the OS into HDD. After you finish the install and clone the partition to PM981, please use 2.

**Comment by arepson** [comment]
I was trying but stuck in SMCRTC Stop

**Comment by arepson** [comment]
![IMG_20200701_075946_compress24](https://user-images.githubusercontent.com/45273945/86191347-ff2b9900-bb70-11ea-816a-902b41dd954e.jpg)

**Comment by arepson** [comment]
How I can restore macOS from HDD to PM981 with paragon? I'm still confused

**Comment by arepson** [comment]
Can give me a link for Paragon Hard Disk Manager™ 16, I can find v17 not v16

**Comment by arepson** [comment]
![IMG_20200701_150256_compress82](https://user-images.githubusercontent.com/45273945/86219265-25225f00-bbac-11ea-88b4-6007b1bef7b3.jpg)
Idk what's wrong'(

**Comment by Tonymiugrey** [comment]
> Can give me a link for Paragon Hard Disk Manager™ 16, I can find v17 not v16

That's OK, don't care about the version... You may search on Google about how to use it.

I don't know what you did...? Did you do a fresh install in the HDD than clone it to SSD？

**Comment by arepson** [comment]
> > Can give me a link for Paragon Hard Disk Manager™ 16, I can find v17 not v16
> 
> That's OK, don't care about the version... You may search on Google about how to use it.
> 
> I don't know what you did...? Did you do a fresh install in the HDD then clone it to SSD？

Yes but PM981 not support update system'( now I'm install on HDD

**Comment by Tonymiugrey** [comment]
> > > Can give me a link for Paragon Hard Disk Manager™ 16, I can find v17 not v16
> > 
> > 
> > That's OK, don't care about the version... You may search on Google about how to use it.
> > I don't know what you did...? Did you do a fresh install in the HDD then clone it to SSD？
> 
> Yes but PM981 not support update system'( now I'm install on HDD

But I have updated success for many versions...
