### ISSUE TITLE
100 Series/C230 Series Chipset Family HD Audio Controller   驱动不了

### ISSUE THREAD

**Issue by ai930** [Tonymiugrey/Garden-by-miugrey#18]
你好，我的黑苹果使用这个引导，100 Series/C230 Series Chipset Family HD Audio Controller  一开始可以驱动。最近就一直驱动不了了。有啥解决办法吗？

**Comment by Tonymiugrey** [comment]
重建驱动完多重启几次试试。我的只是偶尔一两次不能用，一般重启就能解决。

**Comment by ai930** [comment]
我升级到15.5.5了。和这个有关系嘛？
