### ISSUE TITLE
關於無線網卡的問題

### ISSUE THREAD

**Issue by haomaitw** [Tonymiugrey/Garden-by-miugrey#19]
請問這一版網卡驅動都正常嗎？

**Comment by arepson** [comment]
Intel WiFi need ITLWM Kext

**Comment by Tonymiugrey** [comment]
英特尔网卡可以参考以下两种方法：
https://www.bilibili.com/video/BV1Xf4y1y7MJ?from=search&seid=14496919357100527068

http://bbs.pcbeta.com/forum.php?mod=viewthread&tid=1856465&extra=page%3D1%26filter%3Dtypeid%26typeid%3D&page=1
第二种方法不是很稳定，操作起来也比较麻烦，但是可以使用定位服务；第一种相对方便但不能使用定位。

**Comment by arepson** [comment]
I'm still recommended to replace your card or use dongle USB WiFi receiver

**Comment by haomaitw** [comment]
謝謝~

**Comment by Tonymiugrey** [comment]
> I'm still recommended to replace your card or use dongle USB WiFi receiver

Yep

**Comment by Tonymiugrey** [comment]
关于wifi，建议先用heliport: #27
