### ISSUE TITLE
网络问题

### ISSUE THREAD

**Issue by w2016561536** [Tonymiugrey/Garden-by-miugrey#2]
INTEL 9650 [这个无线网卡我放弃了]
但是希望能在包内加上HoRNDIS.kext这个驱动
用于安卓手机通过usb将网络共享给mac
[HoRNDIS.kext.zip](https://github.com/Tonymiugrey/Garden-by-miugrey/files/4396552/HoRNDIS.kext.zip)
在我的光影精灵5 9750h+1660ti 工作稳定且正常

**Comment by Tonymiugrey** [comment]
好的，谢谢反馈！

**Comment by Tonymiugrey** [comment]
为了简化EFI，下个版本将移除这个驱动，如果需要的话请自行安装
