### ISSUE TITLE
Screen Glitch after Sleep

### ISSUE THREAD

**Issue by sirepson** [Tonymiugrey/Garden-by-miugrey#20]
Hi I found new bug, idk what's wrong. My screen glitch after sleep and my second monitor just detect 800×600. first when I used my clover on Github I could detect other resolutions. Can you help me?
<img width="655" alt="Screen Shot 2020-07-04 at 17 18 06" src="https://user-images.githubusercontent.com/45273945/86510592-42a93000-be1b-11ea-9e11-e8e5d07ab220.png">

**Comment by sirepson** [comment]
This is the video when I get glitch screen after sleep
https://streamable.com/dff23x

**Comment by Tonymiugrey** [comment]
Sorry that I don't have another screen... I will compare yours and mine later.

BTW, I'd like to know how to connect the external screen? Through the type-c cable?

**Comment by sirepson** [comment]
How About glitch screen? I'm use USB 3.0 to VGA with Fresco Logic driver

**Comment by sirepson** [comment]
![Screenshot_20200704-203324](https://user-images.githubusercontent.com/45273945/86513595-a8a2b100-be35-11ea-8193-b89598c37ba7.jpg)
https://support.frescologic.com/portal/kb/articles/fl2000-mac-driver-beta-release

**Comment by sirepson** [comment]
I think the problem from USB 3.0, My converter support Full HD+ when detect USB 3.0, when used USB 2.0 the resolution just 800×600. Any patch how to fix the USB 3.0?

**Comment by Tonymiugrey** [comment]
I will release the version that may support usb3.0 soon. Because I don't have usb3.0 devices, so I don't know whether it will work…

**Comment by Tonymiugrey** [comment]
> This is the video when I get glitch screen after sleep
> https://streamable.com/dff23x

This link cannot be opened in China...

**Comment by sirepson** [comment]
Uh I'm sorry, where I can upload video and you support open in China?

**Comment by Tonymiugrey** [comment]
Onedrive if it's convenient for u

**Comment by sirepson** [comment]
https://mannfc88-my.sharepoint.com/:v:/g/personal/ah713_my365office_net/Ecc7pTUvVrBJt8UETNY3WsQBv_nBlYsytKURTu2eIsqkfA?e=KTiPvb

**Comment by Tonymiugrey** [comment]
Which screen? The external screen or the built-in screen?

**Comment by sirepson** [comment]
Built-in screen

**Comment by sirepson** [comment]
before the screen glitch shrinks, it can be corrected by sleeping a second time, but the glitch screen occurs

**Comment by Tonymiugrey** [comment]
Try to enable the HIDPI with the method I mentioned in readme

**Comment by sirepson** [comment]
I'm enable HIDPI :)

**Comment by Tonymiugrey** [comment]
The resolution you set should be 
![image](https://user-images.githubusercontent.com/54355929/86528139-e6581600-bed7-11ea-85a6-fb7786b19cb8.png)

**Comment by sirepson** [comment]
Can I apply this patch to fix USB 3.0? Where patch that I should remove?
https://github.com/Tonymiugrey/Garden-by-miugrey/issues/12#issuecomment-652866503

**Comment by Tonymiugrey** [comment]
You can have a try.
It didn't work on my laptop, made every usb port failed...

**Comment by Tonymiugrey** [comment]
/efi/clover/kext/others/usbinjectall.kext

**Comment by sirepson** [comment]
![IMG_20200705_150302_compress74](https://user-images.githubusercontent.com/45273945/86528304-f28ca500-bed0-11ea-81b1-022e48684f22.jpg)
Before glitch my screen smaller, to fix that must sleep again but get glitch screen

**Comment by Tonymiugrey** [comment]
I know. You should set the resolution of HIDPI to the value I gave you, or this problem will happen.

**Comment by Tonymiugrey** [comment]
3. Enable HiDPI

Run this script in Terminal:

bash -c "$(curl -fsSL https://raw.githubusercontent.com/xzhih/one-key-hidpi/master/hidpi.sh)"
Enter your password.

Choose option 2

image-20200406124116833

Choose option 3

image-20200406124219540

Then option 6, and enter "1472x828".

image-20200406124358629

**Comment by Tonymiugrey** [comment]
I copy this from the readme I wrote.

**Comment by sirepson** [comment]
![IMG_20200705_155356_compress63](https://user-images.githubusercontent.com/45273945/86529080-e8ba7000-bed7-11ea-9010-47286e487265.jpg)
Okay, USB 3.0 now fixed with replace UsbInjectAll.kext.
But glitch screen still not resolved:(

**Comment by sirepson** [comment]
![Screen Shot 2020-07-05 at 16 00 13](https://user-images.githubusercontent.com/45273945/86529166-a3e30900-bed8-11ea-979c-fb2959dedae7.png)

**Comment by Tonymiugrey** [comment]
What is the native resolution of your screen？1080p or 4k？

**Comment by sirepson** [comment]
Hehe it's a old monitor, the resolution monitor just 1440×900

**Comment by Tonymiugrey** [comment]
emm I mean the built-in screen...
If the resolution of your built-in screen is 4k, you need to find the proper hidpi solution for it.
Both two screens are glitch?
Without the external display, will that happen?

**Comment by sirepson** [comment]
Sorry, my built-in screen is 1080p 60hz

**Comment by Tonymiugrey** [comment]
That's strange... :(

**Comment by Tonymiugrey** [comment]
I'm 1080 too and everything works well.

**Comment by sirepson** [comment]
![IMG_20200705_162252_compress7](https://user-images.githubusercontent.com/45273945/86529591-0558a700-bedc-11ea-9379-7a002a106eb4.jpg)
Fist sleep my built-in screen get more smaller, and after second sleep back to normal but in built-in screen glitch

**Comment by Tonymiugrey** [comment]
I know that... It's caused by the improper hidpi resolution. Are you sure that you set the resolution to the one I gave you and restart the computer?

**Comment by sirepson** [comment]
![Screen Shot 2020-07-05 at 16 27 46](https://user-images.githubusercontent.com/45273945/86529650-7ef09500-bedc-11ea-8e41-17177e7b2ac3.png)
When I select default the glitch screen gone

**Comment by sirepson** [comment]
> I know that... It's caused by the improper hidpi resolution. Are you sure that you set the resolution to the one I gave you and restart the computer?

Yes, I follow your method because my screen is 1080p

**Comment by sirepson** [comment]
I'm use i7-9750H ++ GTX1650

**Comment by Tonymiugrey** [comment]
Could you show me the following information on the resolution that caused the glitch?
![image](https://user-images.githubusercontent.com/54355929/86529694-646ee980-bee5-11ea-9fd6-9efd42060e4f.png)
![image](https://user-images.githubusercontent.com/54355929/86529726-941df180-bee5-11ea-918f-f5d6890e958c.png)
1920x1080 is ok if you like it. For me, the words on the screen are too small.
Also, it seems that 1920x1080 may cause a crash reboot when it sleeps. I'm not sure about that.

**Comment by sirepson** [comment]
<img width="783" alt="Screen Shot 2020-07-05 at 16 38 31" src="https://user-images.githubusercontent.com/45273945/86529818-fc68d500-bedd-11ea-8842-d2ae680258b2.png">

**Comment by Tonymiugrey** [comment]
It will glitch under this resolution right?

**Comment by sirepson** [comment]
<img width="638" alt="Screen Shot 2020-07-05 at 16 41 23" src="https://user-images.githubusercontent.com/45273945/86529873-7436ff80-bede-11ea-9a3b-481d3e4c51d0.png">
<img width="630" alt="Screen Shot 2020-07-05 at 16 41 34" src="https://user-images.githubusercontent.com/45273945/86529878-77ca8680-bede-11ea-983e-3666fce3518b.png">
<img width="647" alt="Screen Shot 2020-07-05 at 16 41 43" src="https://user-images.githubusercontent.com/45273945/86529880-78fbb380-bede-11ea-868e-87e465d97c9f.png">
<img width="636" alt="Screen Shot 2020-07-05 at 16 41 50" src="https://user-images.githubusercontent.com/45273945/86529881-79944a00-bede-11ea-8feb-566402082516.png">

**Comment by sirepson** [comment]
> It will glitch under this resolution right?

Yes, right. idk whats wrong. 
can we ask for help to tonymacx86?

**Comment by Tonymiugrey** [comment]
Of course.
And here is a way that may help you. Calculate all the resolutions as the proportion of 16:9, such as 1920x1080 or 1742x828... Then choose a resolution one by one until you find the one that will not cause that problem. I got 1742x828 through this method haha and it works fine on my computer.

**Comment by sirepson** [comment]
I'm try your resolution but still glitch haha, forget about this bug. I'm still waiting about your OC, I don't understand about OC. Maybe you can help me:)

**Comment by sirepson** [comment]
![IMG_20200705_170027_compress42](https://user-images.githubusercontent.com/45273945/86530230-253e9980-bee1-11ea-8fe1-35b87bf5ee07.jpg)
This the screen glitch when I reboot

**Comment by Tonymiugrey** [comment]
OMG it's horrible
Try to find the solution that will not cause glitch for yourself~
OC seems a little bit hard for me... Maybe you need to wait for a period :0

**Comment by sirepson** [comment]
I think the glitch screen fix (not input manual but choose option 2)

**Comment by sirepson** [comment]
You can close this issue after I tested in 3 days

**Comment by sirepson** [comment]
![5824](https://user-images.githubusercontent.com/45273945/86530360-5ec3d480-bee2-11ea-9f3a-8656716a23c3.png)
Choose option 2

**Comment by Tonymiugrey** [comment]
That will cause the glitch and half-screen on my computer although the Chinese in the bracket means option 2 will fix it haha that's weird.
I will update readme about this. Thanks!

**Comment by sirepson** [comment]
I suggest to mention your spec in readme.md and which features are not performed.
HDMI port is connected with disabled NVIDIA DGPU.

**Comment by Tonymiugrey** [comment]
OK thx! I will

**Comment by sirepson** [comment]
Are you ready for Big Sur?:)

**Comment by Tonymiugrey** [comment]
A buggy OC... There're still many problems. Touchpad doesn't work and sleep is unnormal. I'm sure that there're more bugs that I have not found :( Give me some times...

**Comment by sirepson** [comment]
Keep calm, btw thanks for your contribution. Maybe you can check olarila forum to request DSDT Patch. Have a great day Tony

**Comment by Tonymiugrey** [comment]
THX!😁
