### ISSUE TITLE
键盘和刷新率问题

### ISSUE THREAD

**Issue by w2016561536** [Tonymiugrey/Garden-by-miugrey#22]
3.1版本的efi文件的bug,在fn快捷键长按后整个键盘会被禁用掉
而且以前2.1版本调整刷新率都不需要hidpi(省点)

**Comment by Tonymiugrey** [comment]
都没碰到过这些问题。我现在不用独显的时候都只用mac Windows很久没碰了。用得很舒服，基本没问题。我感觉不同电脑硬件上可能会有些差别 自行根据情况百度解决

刷新率不是一直都不用hidpi吗？3.1把之前没成功禁用的独显彻底禁用了，省电很多。

**Comment by Tonymiugrey** [comment]
确实发现了无法调整刷新率的问题……我再hidpi下面没有看到刷新率的选项 不过我的是60hz的屏幕，也没必要调刷新率……之后会再研究 你换回2.1然后在开启hidpi试试看有没有这个选项 我猜测这和HIDPI脚本下载的显示器的配置文件有关系，因为我确实没有在显示器和核显这块做过修改

**Comment by Tonymiugrey** [comment]
对了突然想起来 你去bios里面把F1-F12设置为功能键试试 我一直是这么设置的 没出现过问题

**Comment by Tonymiugrey** [comment]
记得重建缓存

**Comment by w2016561536** [comment]
我的意思是在无hidpi下，3.1无刷新率选项
2.1可以在无hidpi下切刷新率（这玩意真的耗电）
此外3.1的键盘功能键按住bug在重建缓存重启后依然存在，2.1就无问题（无论bios里设置是否需要fn组合键）

键盘被禁用指的是只有键盘f5功能键（键盘背光）有响应

**Comment by w2016561536** [comment]
换回2.1.1的efi试了一下，这个bug还是存在的！！！（不知道以前为啥没注意到）
这个bug就像玩mc一样，一直按住一个键时间过长，你人物就无法再控制方向了，会朝着一个方向走。

**Comment by w2016561536** [comment]
目前唯一的曲线救国方式是，不要长按快捷键，需要一下一下按，否则只有重启解决。

**Comment by Tonymiugrey** [comment]
可是我真的没动过核显和显示器相关的内容啊…你要是提起我也没发现……（BTW你的续航怎么样？我是60hz屏，也没什么必要调刷新率，Win性能限制一下能用4个小时多 mac能用3小时半）
键盘问题我也遇到过，但是用了这一年也就两三次吧…刚刚我按住连续几次来回调了音量和亮度也没事……………不过我估计是ssdt问题 最近在折腾OC 等做到亮度快捷键这块的时候会再关注一下的

**Comment by w2016561536** [comment]
续航正在测试中，50%的亮度，144刷新率，一小时掉电30%,

**Comment by Tonymiugrey** [comment]
那确实有点捉急……你把2.1里面 acpi/patched文件夹里的东西都删掉换成3.1里面的试试看刷新率会不会回来

**Comment by w2016561536** [comment]
那根本启动不了

**Comment by Tonymiugrey** [comment]
？不至于 你再重启试试 我自己改的我清楚……

**Comment by w2016561536** [comment]
好吧，这是个玄学问题，现在能看到苹果标了，之前一直卡在uefi的光标那里

**Comment by w2016561536** [comment]
2.1.1的efi用3.1的patch在无hidpi下依然有刷新率控制选项

**Comment by w2016561536** [comment]
还是不稳定，重启后依然clover加载不出来，屏幕上只有光标

**Comment by Tonymiugrey** [comment]
你用hackintool里面的显示器做一个补丁放进3.1的试试 我电脑放在家里了不能试

**Comment by Tonymiugrey** [comment]
关于刷新率，突然猜到原因了，但是**可能**不打算修复……因为涉及到黑苹果的完美程度
你试试在2.1的efi下查看是否成功启用硬解 或者装个Geekbench 在Compute里面选择Metal进行跑分，看看能不能顺利跑分

**Comment by w2016561536** [comment]
好久没看github了，2.1.1的efi在系统报告，图形卡中，显示支持metal，功能集macos gpufamily2 v1,芯片组型号是intel uhd graphics 630

还是是不是掉声卡驱动,所以我插了一个c口耳机，发现使用耳机线控音量就没有这个bug

**Comment by Tonymiugrey** [comment]
你要按我说的去试试我才能判断问题 这样看没用的

**Comment by Tonymiugrey** [comment]
测试了很多次，我目前的clover存在长按亮度按键后全部按键失灵的情况，但是音量键再怎么按都不会。估计在我之后的OC里面会先修复这个问题。

**Comment by ai930** [comment]
你声卡可以驱动吗？
