### ISSUE TITLE
光影5的BIOS隐藏项修改

### ISSUE THREAD

**Issue by w2016561536** [Tonymiugrey/Garden-by-miugrey#25]
上次你说可以通过修改bios来达到某些省电的目的，然后我买了编程器。
有什么修改的思路吗。

**Comment by Tonymiugrey** [comment]
主要是CFG Lock这个选项需要关闭 不过现在不影响了 Clover和OC都有相关的设置

关于BIOS你看看这个 我之前试过但是没成功 按理来说暗影5可以光影5应该也是可以的
http://tieba.baidu.com/p/6497505154?share=9105&fr=share&unique=24FFDDE868BE8F43F0FE2C10871BBB0F&st=1594730523&client_type=1&client_version=11.6.1&sfc=copy

**Comment by Tonymiugrey** [comment]
具体需要修改的内容你可以看看其他一些关于黑苹果BIOS设置的文章，我记得就是CFG Lock关掉 还有一个叫DV啥啥啥的一个东西 改成64MB

**Comment by w2016561536** [comment]
问题是，insyde的bios不允许用户修改一些键值，现在的方法都是利用修改BIOS的默认值来修改键值

**Comment by Tonymiugrey** [comment]
怎样了

**Comment by ai930** [comment]
你声卡可以驱动吗？
