### ISSUE TITLE
HDMI接口可以使用吗 需要进行什么配置吗？

### ISSUE THREAD

**Issue by yqLiu2019** [Tonymiugrey/Garden-by-miugrey#26]
最近有买了一个显示器，想外接一下黑苹果。

说一下情况：
macOS10.15.6 beta4
笔记本 i5 9300H
显示器 4k hdmi2.0 win下正常可用。

请教胰腺癌这个CLOVER有包含HDMI功能吗？ 因为我看到enableHDMI20好像是开启的，也用了 lilu 和 whateverGreen 但是又不能外接显示器就很奇怪

**Comment by ghost** [comment]
> 最近有买了一个显示器，想外接一下黑苹果。
> 
> 说一下情况：
> macOS10.15.6 beta4
> 笔记本 i5 9300H
> 显示器 4k hdmi2.0 win下正常可用。
> 
> 请教胰腺癌这个CLOVER有包含HDMI功能吗？ 因为我看到enableHDMI20好像是开启的，也用了 lilu 和 whateverGreen 但是又不能外接显示器就很奇怪

HDMI is connected on nvidia gpu, and not working on macOS !

**Comment by sirepson** [comment]
https://github.com/Tonymiugrey/Garden-by-miugrey/issues/20#issuecomment-653766085

**Comment by yuzhanglong** [comment]
https://github.com/Tonymiugrey/Garden-by-miugrey/issues/15

**Comment by yqLiu2019** [comment]
谢谢大佬们 我尝试一下 typec - dp 和 USB - HDMI的方案

**Comment by sirepson** [comment]
Make sure your Converter USB 3.0 to HDMI support Fresco Logic Driver

**Comment by Tonymiugrey** [comment]
怎么样了
