### ISSUE TITLE
Windows Entry in OpenCore

### ISSUE THREAD

**Issue by arepson** [Tonymiugrey/Garden-by-miugrey#28]
When I check config.plist from OpenCore Thunderobot 911 (https://github.com/athlonreg/Thunderobot-911-Air-i7-9750h)
I'm find this line
`		<key>Entries</key>
		<array>
			<dict>
				<key>Arguments</key>
				<string></string>
				<key>Auxiliary</key>
				<false/>
				<key>Comment</key>
				<string>Windows</string>
				<key>Enabled</key>
				<true/>
				<key>Name</key>
				<string>Windows</string>
				<key>Path</key>
				<string>PciRoot(0x0)/Pci(0x1D,0x0)/Pci(0x0,0x0)/NVMe(0x1,00-00-00-00-00-00-00-00)/HD(1,GPT,466BCBA0-2376-4603-AFD6-58CDE11CBE10,0x28,0x64000)/\EFI\Microsoft\Boot\bootmgfw.efi</string>
			</dict>
		</array>`
Maybe you can try to fix Windows Entry in Opencore.

**Comment by arepson** [comment]
You can compare with Thunderobot 911 and HP Pavilion Gaming 15 dk0xxx because have similiar hardware

**Comment by Tonymiugrey** [comment]
I think the problem is about SSDT.

**Comment by arepson** [comment]
I'm sorry'( But I can't help you, I don't understand about advanced Hackintosh

**Comment by Tonymiugrey** [comment]
That's OK
