### ISSUE TITLE
我这一直声卡驱动不了

### ISSUE THREAD

**Issue by ai930** [Tonymiugrey/Garden-by-miugrey#29]
AppleALC一直驱动不了，网上说注入id 试过了很多id 都不行啊！作者有考虑声卡驱动吗？

Realtek ALC285 @ Intel Cannon Point PCH - cAVS (Audio, Voice, Speech) [B0]

**Comment by Tonymiugrey** [comment]
我都用了一年了…你试试重建缓存
一般是21或者31
目前的问题是偶尔会发生重启后声卡突然不能用 再重启就好了
正常使用是可以的

**Comment by ai930** [comment]
发布贴一下你的配置文件吗？注入那块的补丁

**Comment by Tonymiugrey** [comment]
就直接用我release里面的clover就行了啊

**Comment by ai930** [comment]
我这里试了不行！release里面的clover没有声卡注入部分啊！我怀疑是我的注入配置哪里写额有问题

**Comment by Tonymiugrey** [comment]
![截屏2020-09-06 下午12 45 10](https://user-images.githubusercontent.com/54355929/92318455-de833200-f03e-11ea-8b4c-2c07491a8c31.png)
自己研究

**Comment by ai930** [comment]
CLOVER2 这个文件夹吗？里面没见你的声卡注入啊

**Comment by Tonymiugrey** [comment]
是Clover2 截图里面都展示的很清楚了 我用hackintool注入的 你去研究小兵那篇文章

**Comment by ai930** [comment]
![image](https://user-images.githubusercontent.com/6250892/92326968-b6b8bc00-f088-11ea-974e-fe4a816b60c9.png)

![image](https://user-images.githubusercontent.com/6250892/92326983-d4862100-f088-11ea-937b-07189ffc51e8.png)

打开hackintool发现注入不进去。试了你的配置也不行。然后我又手动添加了一些配置还是不行：
![image](https://user-images.githubusercontent.com/6250892/92327015-2a5ac900-f089-11ea-8598-dd7438289792.png)

求大神给点思路呗！
