### ISSUE TITLE
安装

### ISSUE THREAD

**Issue by w2016561536** [Tonymiugrey/Garden-by-miugrey#3]
推荐一个安装方法，不用第二块硬盘
1windows创建一个分区,随便格式化
2使用VMware,打上unlock macos补丁
3在vmvare创建虚拟机，安装光盘选择官方cdr镜像，磁盘设置的越小越好(这个磁盘没啥用)
4完成创建后，编辑虚拟机，然后添加磁盘，选择刚刚格式化好的分区，保存
5启动虚拟机，然后安装在分区里。
6clover放进磁盘的esp分区里，重启计算机，从efi启动

**Comment by w2016561536** [comment]
而且这样可以节省ssd寿命

**Comment by Tonymiugrey** [comment]
Thanks a lot!

**Comment by Tonymiugrey** [comment]
是通过虚拟机直接安装在实体硬盘上吗

**Comment by w2016561536** [comment]
> 是通过虚拟机直接安装在实体硬盘上吗

是的，所以这样可以节省时间和ssd寿命

**Comment by Tonymiugrey** [comment]
好的，感谢！能否分享一下所需软件的下载链接？

**Comment by w2016561536** [comment]
并且以后更新系统的时候，可以直接在虚拟机更新(因为虚拟机和物理机共享磁盘分区)，不用重做系统

**Comment by Tonymiugrey** [comment]
我这儿是可以直接在macOS里更新系统的

**Comment by Tonymiugrey** [comment]
最近解决了耗电问题，但仅限于睡眠之前。。睡眠唤醒之后又开始续航尿崩 很夸张的那种

**Comment by Tonymiugrey** [comment]
过段时间放EFI，打算这几天在tonymacx86里寻求大佬帮助

**Comment by w2016561536** [comment]
好的，这个首先需要vmvare的15.5版本（网上有激活码和安装包，太大不上传了，windows1909运行不了老版本的vmware）
还有unlocker macos工具，摘自某个GitHub页面，但原页面找不到了
[mac10.15-16-Unlocker-VM15.5.zip](https://github.com/Tonymiugrey/Garden-by-miugrey/files/4436662/mac10.15-16-Unlocker-VM15.5.zip)
安装好vmware，解压以后以管理员运行win-install.cmd就好
建议断网运行（下载vmtools很耗时间）
等待脚本退出，就能在创建虚拟机里看见macos选项了

**Comment by Tonymiugrey** [comment]
好的！感谢！

**Comment by reyan639** [comment]
按照上述方法，抹掉磁盘时出错，不知道为什么

**Comment by w2016561536** [comment]
> 按照上述方法，抹掉磁盘时出错，不知道为什么

抱歉，的确是我测试的时候疏忽了，我在测试的时候，目标分卷已经格式化成了apfs，所以可以正常写入，但是对于NTFS刚刚测试了一下，可以用diskutil格式化并写入，但无法引导

**Comment by w2016561536** [comment]
> 按照上述方法，抹掉磁盘时出错，不知道为什么

可能不需要第二块硬盘的方法只有克隆vmdk虚拟磁盘文件，或者等待Windows上的APFS的分区工具

**Comment by Tonymiugrey** [comment]
在安装器里面格盘是需要硬盘上有efi分区的，不懂vm能不能挂载efi分区

记得diskgenius可以格式化为apfs格式的

**Comment by reyan639** [comment]
> > 按照上述方法，抹掉磁盘时出错，不知道为什么
> 
> 可能不需要第二块硬盘的方法只有克隆vmdk虚拟磁盘文件，或者等待Windows上的APFS的分区工具

好的，谢谢

**Comment by w2016561536** [comment]
> 在安装器里面格盘是需要硬盘上有efi分区的，不懂vm能不能挂载efi分区
> 
> 记得diskgenius可以格式化为apfs格式的

这个vm好像就是有大佬给他写了专属efi，diskgenius可以将磁盘设置为APFS容器，但不能在容器里格式化出来卷宗
