### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by VladAlexandru2000** [Tonymiugrey/Garden-by-miugrey#32]
![1AA5A6D0-9A56-42B6-BC89-BB384E1DBE53](https://user-images.githubusercontent.com/66947407/99156047-75ffa380-26c6-11eb-9a5b-1b6ae65e3e6b.jpeg)

**Comment by Tonymiugrey** [comment]
Have you solved that?

**Comment by VladAlexandru2000** [comment]
yes
