### ISSUE TITLE
OpenCore default boot option !

### ISSUE THREAD

**Issue by VladAlexandru2000** [Tonymiugrey/Garden-by-miugrey#33]
How can I make OpenCore boot when starting the laptop instead of Micorosoft Boot Manager?

**Comment by arepson** [comment]
I'm try to delete Windows EFI but my OpenCore not detect in BIOS'( So when I used Windows Boot Manager, I have to manually enter OpenCore with F9 button.

**Comment by Tonymiugrey** [comment]
Try EasyUEFI, delete Microsoft EFI, add a new item and manually choose opencore.efi, then make it top, restart

**Comment by Tonymiugrey** [comment]
> Try EasyUEFI, delete Microsoft EFI, add a new item and manually choose opencore.efi, then make it top, restart

Oh sorry, disable it, not delete.
It will appered again if you delete it, but if you disable it, it will never appear.
