### ISSUE TITLE
Return From Sleep Not Working !

### ISSUE THREAD

**Issue by ghost** [Tonymiugrey/Garden-by-miugrey#34]

**Comment by ghost** [comment]
I'am not using PM981

**Comment by ghost** [comment]
On Raffay Sajjad OC sleep work perfect

**Comment by ghost** [comment]
what changes should I make to work on your OC as well?

**Comment by VladAlexandru2000** [comment]
I found fix ! 
![56F0C18A-E032-4B7B-8997-5AB0E4598A30](https://user-images.githubusercontent.com/66947407/99187570-08a05100-2760-11eb-946a-a58e85251c7e.jpeg)

**Comment by ghost** [comment]
I solve the problem !

**Comment by sirepson** [comment]
How to solve?

**Comment by ghost** [comment]
I will send you my EFI file a little later stating that I do not have an intel or SSD PM981 network card!

**Comment by ghost** [comment]
I found another problem, brightness keys not working ☹️ and return to sleep not working again ☹️

**Comment by ghost** [comment]
I will delete the MacOS until Tonymiugrey fixes this annoying bug! 😢

**Comment by Tonymiugrey** [comment]
It seems that big sur is unfriendly with PM981 and I still can't boot into big sur, with the kp message about nvme...
Maybe I will back to Catalina until patches for PM981 work normally in big sur
I will try to fix the problems you mentioned in Catalina.
![787F98C8-46CF-4552-917D-051B31AEBD18](https://user-images.githubusercontent.com/54355929/99564613-a1a3c600-2a05-11eb-8181-34ad85b90ce1.png)

**Comment by ghost** [comment]
I'm sorry man, I was annoyed by that ssd and I took it out, now I use RaffaySajjad's opencore EFI where the sleep mode works perfectly even on Big Sur, the only thing that annoys me is that I can't start Windows with it.
Honestly I would like to know why Windows starts on your EFI perfectly, and it gives me BSOD (ACPI_BIOS_ERROR) if you can tell me what to change so that I can start Windows, it would be wonderful!

**Comment by Tonymiugrey** [comment]
Ok guys i made it hahaha
![E499C6EC-DF23-4377-8CF1-59B480F83A24](https://user-images.githubusercontent.com/54355929/99570749-60171900-2a0d-11eb-941b-95ebc8ce40b8.jpeg)

**Comment by ghost** [comment]
Verryy nice man ! Now test return from sleep !

**Comment by ghost** [comment]
help me to solve another problem touchpad on windows when boot from opencore

**Comment by sirepson** [comment]
> Verryy nice man ! Now test return from sleep !

I don't know what's wrong, but sleep in my SSD working well. I'm use OpenCore for folder Other SSD. Have you try to reset NVRAM or rebuild cache?

**Comment by ghost** [comment]
I do that and don t work and i try to reinstall mac os and don t work

**Comment by sirepson** [comment]
Maybe something different from your laptop, depending your country. I hope @Tonymiugrey can help you. OpenCore from Tony is Perfect 🥺👍 thank you Tony.

**Comment by Tonymiugrey** [comment]
> help me to solve another problem touchpad on windows when boot from opencore

Touchpad should works normal in Windows.
.. At least on my laptop it works well...

**Comment by ghost** [comment]
for you sleep working ?

**Comment by Tonymiugrey** [comment]
> for you sleep working ?
Sometimes it is ok but most of time it cannot wake  from sleep and give a nvme error.

**Comment by ghost** [comment]
at me is not a nvme error remains black and force restart

**Comment by ghost** [comment]
Strange is that on RaffaySajjad's EFI the sleep mode works and on Tony's EFI it doesn't work!

**Comment by Tonymiugrey** [comment]
nvme caused kp again when booting...

**Comment by ghost** [comment]
☹️

**Comment by ghost** [comment]
on your device brightness keys working ?

**Comment by Tonymiugrey** [comment]
yes

**Comment by ghost** [comment]
how can i fix it, at the moment it all works except the brightness keys ?

**Comment by Tonymiugrey** [comment]
have you changed something？

**Comment by ghost** [comment]
i fixed the problem, i rebuild SSDT-Backlight and now work perfect

**Comment by ghost** [comment]
and sleep problem fixed with disable hibernate mode and delete hibernatefixup.kext

**Comment by Tonymiugrey** [comment]
Thanks! I have already delete it and I will try to disable hibernate mode later

**Comment by Tonymiugrey** [comment]
> i fixed the problem, i rebuild SSDT-Backlight and now work perfect

Maybe you should back to Windows and test whether is it normal in Windows.

**Comment by ghost** [comment]
On windows all working perfect!

**Comment by ghost** [comment]
I noticed a very strange thing when I turn on the laptop and it is not connected to the socket, TurboBoostDisable does not work, it only works when I connect the laptop to the socket and then I disconnect it!

**Comment by Tonymiugrey** [comment]
> On windows all working perfect!

Nice

**Comment by Tonymiugrey** [comment]
> I noticed a very strange thing when I turn on the laptop and it is not connected to the socket, TurboBoostDisable does not work, it only works when I connect the laptop to the socket and then I disconnect it!

Maybe it is a bug of Disableturbo boost

**Comment by ghost** [comment]
I tried to install mac os on a separate disk and windows on another disk and apparently rebooting from mac to windows works, but not the other way around!

**Comment by Tonymiugrey** [comment]
Try to boot windows through OC
I works for me

**Comment by Tonymiugrey** [comment]
> Try to boot windows through OC
> I works on my computer

**Comment by ghost** [comment]
The Boot Camp Assistant works perfectly but does not recognize the disk on which I installed the mac os (a samsung 860 evo)

**Comment by Tonymiugrey** [comment]
I have said I can't help you with that. Try to install it on a same SSD

**Comment by ghost** [comment]
Is not a problem for me, thank you for help me with your EFI ! Keep Up the Good Works !

**Comment by ghost** [comment]
I will close this issue ! Thank you again !
