### ISSUE TITLE
What exactly does Innie.kext do?

### ISSUE THREAD

**Issue by ghost** [Tonymiugrey/Garden-by-miugrey#36]

**Comment by VladAlexandru2000** [comment]
And another thing, when update PS2Controller.kext cause problem and keyboard not working ?

**Comment by ghost** [comment]
When MacOS is installed on nvme 970 evo sleep mode not working 😢 ! Perfect working only on sata 860 evo ! 
Installing both systems on a single ssd is not possible so I can't use bootcamp !

**Comment by Tonymiugrey** [comment]
Google.
