### ISSUE TITLE
There may be a problem with the Big Sur with the NVMe!

### ISSUE THREAD

**Issue by ghost** [Tonymiugrey/Garden-by-miugrey#38]
I have a 970 evo that I have Big Sur and when I get out of sleep I get karnel panic nvme fatal error!
I tried to install Catalina with your EFI and everything works perfectly so I think it's a problem with Big Sur!

**Comment by Tonymiugrey** [comment]
There's a new possibility that the problems about nvme we met are caused by an unproper setting of EC. I'm not sure about that and will check this later.

**Comment by ghost** [comment]
SSDT-EC ?

**Comment by Tonymiugrey** [comment]
Maybe... I just heard something about that. Further confirm is needed.

**Comment by ghost** [comment]
ALL work perfect for me but problem is sleep, after return from sleep, screen keep black and in short time reboot, after enter in macOS again, error report show kp nvme fatal error !
I used OC for other SSD because i don t have a PM981

**Comment by ghost** [comment]
Can I try to use HackrNVMeFamily for my Samsung 970 Evo SSD?

**Comment by Tonymiugrey** [comment]
Test it by yourself.

**Comment by ghost** [comment]
I have fixed my problem, replaced 970 evo with an SEAGATE FIRECUDA 510 with PHISON controller, all work perfect and verry fast, boot and apps thanks for your OC !
PHISON controller is perfect for macOS !
