### ISSUE TITLE
用了光影五的efi经常会出现applenvme assert failed

### ISSUE THREAD

**Issue by reyan639** [Tonymiugrey/Garden-by-miugrey#4]
![IMG_20200422_093554](https://user-images.githubusercontent.com/63842654/79935739-3ce0b700-8488-11ea-9e80-ebd62ad23e1c.jpg)
![IMG_20200422_093612](https://user-images.githubusercontent.com/63842654/79935744-3f431100-8488-11ea-86db-dcc5e0d3cea0.jpg)

**Comment by Tonymiugrey** [comment]
你的硬盘是PM981吗

**Comment by reyan639** [comment]
是的，可能是硬盘的问题

**Comment by Tonymiugrey** [comment]
请确定硬盘型号，按照我在Readme里写的进行操作。我的硬盘是PM981，没有碰到这种情况。

**Comment by Tonymiugrey** [comment]
请问是否解决？
