### ISSUE TITLE
Project Restart

### ISSUE THREAD

**Issue by Tonymiugrey** [Tonymiugrey/Garden-by-miugrey#43]
For some reasons, I will restart this project with a new SSD(not PM981) and Broadcom wireless card. I will try to install Monterey and later the newest Ventura once it is released.
So PM981 and Intel wireless card will be no longer supported.

**Comment by Helio-x** [comment]
Nice efi, your efi are the most stable I've ever used. I found some other efi for monterery on other website, they have some mistake and I can't solve... so I still use Big Sur. I'm looking forward to your new efi. Thank you very much。

**Comment by Tonymiugrey** [comment]
> Nice efi, your efi are the most stable I've ever used. I found some other efi for monterery on other website, they have some mistake and I can't solve... so I still use Big Sur. I'm looking forward to your new efi. Thank you very much。

Thank u and I will release the one for monterey this night
But i'm afraid that i will make this repo archived again because i will sell this laptop in these days.

**Comment by Tonymiugrey** [comment]
Chinese user?haha 看到你的句号是中文的

**Comment by Tonymiugrey** [comment]
> Nice efi, your efi are the most stable I've ever used. I found some other efi for monterery on other website, they have some mistake and I can't solve... so I still use Big Sur. I'm looking forward to your new efi. Thank you very much。

Chinese user?haha 看到你的句号是中文的

**Comment by Helio-x** [comment]
> > Nice efi, your efi are the most stable I've ever used. I found some other efi for monterery on other website, they have some mistake and I can't solve... so I still use Big Sur. I'm looking forward to your new efi. Thank you very much。
> 
> Chinese user?haha 看到你的句号是中文的

哈哈，感谢老哥的efi，我最近试了试google的几个monterey的efi，应该都是一个，都存在开机白苹果之后黑屏几十秒才能登陆的问题，而且我一直驱动不了网卡和蓝牙，也不想换博通网卡，只能慢慢折腾了。

**Comment by Tonymiugrey** [comment]
超 我之前换了电脑后 旧的efi一直放在桌面上 刚刚折腾完新电脑的黑果后随手吧桌面乱七八糟的东西一删 清空回收站……gg
给个思路吧 如果你换了PM981的话，就下载我那个for other ssd， 然后吧oc和kext全部更新一遍 基本就可以了
其中英特尔wifi的那个驱动要去它github release页上下载monterey的版本
没换pm981的话也是gg 用不了的
