### ISSUE TITLE
我这个死活都装不上，一直卡在please go to

### ISSUE THREAD

**Issue by Chenvh** [Tonymiugrey/Garden-by-miugrey#5]

**Comment by Tonymiugrey** [comment]
你按照readme里面说的做了吗

**Comment by Chenvh** [comment]
对，我是傲腾的盘，用的是那个other clover ，-v跑马，取消重启，改macbook 13,4。原版的clover，大佬你的clover，llilu换最新版的。都试了一遍，还是卡go

**Comment by Tonymiugrey** [comment]
傲腾的我没测试过…你可以去找找有没有别的电脑的efi 用同款硬盘的

**Comment by Tonymiugrey** [comment]
然后把相关文件整合进我的efi试试

**Comment by Tonymiugrey** [comment]
成功了吗

**Comment by Chenvh** [comment]
没呢！一直卡go，暂时不想折腾了
