### ISSUE TITLE
显示条纹、显示器扩展问题

### ISSUE THREAD

**Issue by xxy9468615** [Tonymiugrey/Garden-by-miugrey#8]
你好，安装后显示视频出现条状纹理，视频感觉很别扭，还有就是显示器无法扩展问题能解决吗？

**Comment by Tonymiugrey** [comment]
1.没遇到这种情况，我的一切正常
2.HDMI口是连在独显上的，所以用不了，typeC口因为我手上没有设备所以无法测试

**Comment by Tonymiugrey** [comment]
第一个问题 能否描述具体细节并配图 不太清楚你遇到了什么

**Comment by xxy9468615** [comment]
HDMI口是连显示器无法显示，typeC口没用。
第一个就是视频画面会出现横条纹现象，画质不是很好。

**Comment by xxy9468615** [comment]
规格：Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
           16 GB     8GB Samsung 2667MHz            8GB 04CB 2667MHz
           Intel(R) UHD Graphics 630           NVIDIA GeForce GTX 1650

**Comment by Tonymiugrey** [comment]
这部机器的HDMI是连在独显上的，在macOS里本来就不能用，常识；真的没遇到过这种情况，确认一下是不是所有视频都是这样，自己你Hidpi选择的分辨率是不是和我readme里面写的一样
