### ISSUE TITLE
DK-0199TX 卡在SMCRTC: Cannot read PMU offset from SMC

### ISSUE THREAD

**Issue by Keison-5741** [Tonymiugrey/Garden-by-miugrey#9]
不曉得您看不看到的圖片?
[https://drive.google.com/file/d/19aqDLLjJVTcYhmRInf_EYcFMtcEudm1U/view?usp=sharing](url)

**Comment by Tonymiugrey** [comment]
没遇到这种问题…按照readme里面的做了吗

**Comment by Keison-5741** [comment]
我完全複製您的efi，將clover1 改成efi，放進eps區，跑verbose模式就卡在那畫面了。

**Comment by Tonymiugrey** [comment]
我晚些给你发一个config试试 你替换一下

**Comment by Tonymiugrey** [comment]
把我给你的文件直接贴进原来的clover1里面 我弄了两种可能的方法 
[tests.zip](https://github.com/Tonymiugrey/Garden-by-miugrey/files/4575165/tests.zip)
你都尝试一下

**Comment by Keison-5741** [comment]
好的，感謝您!

**Comment by Tonymiugrey** [comment]
成功了吗

**Comment by Keison-5741** [comment]
您好!
因為notebbok不是我本人的，所以短時間內無法再次測試，所以無法繼續玩了。
